general:
  kafka-topic: trader-updates

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: midas-core
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"